// ============================================================================
// Structured financial terms per scheme — the numbers the calculation engine
// is allowed to use. Nothing here is generated by AI.
//
// PROVENANCE. Each term is tagged:
//   'repo'      — taken from the scheme's own fields/text in data/schemes.js
//   'guideline' — from the scheme's published operational guidelines; the UI
//                 tells the user to confirm these with the bank/portal
// Anything not known is left null/'unspecified' and the engine reports it as
// unknown rather than guessing. In particular NO interest rate is ever invented
// for a scheme that says "bank's normal rate".
//
// Money is in rupees. Percentages are plain numbers (25 = 25%).
// ============================================================================

const MANUFACTURING_GROUP = ['manufacturing', 'food_processing', 'handicrafts', 'agriculture_allied'];
const SPECIAL_CATEGORIES = ['sc', 'st', 'obc', 'minorities'];

export const CURATED_TERMS = {
  scheme_pmegp: {
    fundingType: 'loan_with_subsidy',
    sizeMin: 100000, // repo
    sizeMax: ({ sector }) => (MANUFACTURING_GROUP.includes(sector) ? 5000000 : 2000000), // repo: ₹50L manufacturing, ₹20L services/trade
    ownContributionPct: ({ special }) => (special ? 5 : 10), // guideline
    grant: {
      kind: 'pct_of_cost',
      pct: ({ special, area }) => ({ rural: special ? 35 : 25, urban: special ? 25 : 15 }[area] ?? null), // repo ranges (rural 25–35%, urban 15–25%) + guideline split
      timing: 'back_ended', // subsidy is credited to the loan account later — never netted from the EMI here
    },
    rate: { kind: 'unspecified', note: 'The loan is at the bank\'s normal rate; the scheme does not fix it.' },
    sources: { size: 'repo', rate: 'repo', own: 'guideline', grant: 'repo+guideline' },
    verifyWithBank: ['own_contribution', 'subsidy_split'],
    specialCategories: SPECIAL_CATEGORIES,
    specialIfFemale: true,
  },
  scheme_mudra_shishu: {
    fundingType: 'loan',
    sizeMin: 10000, sizeMax: 50000, // repo
    ownContributionPct: null,
    grant: null,
    rate: { kind: 'range', min: 8.5, max: 10 }, // repo
    sources: { size: 'repo', rate: 'repo' },
    verifyWithBank: ['rate'],
  },
  scheme_mudra_kishore: {
    fundingType: 'loan',
    sizeMin: 50000, sizeMax: 1000000, // repo
    ownContributionPct: null,
    grant: null,
    rate: { kind: 'range', min: 9, max: 11.5 }, // repo
    sources: { size: 'repo', rate: 'repo' },
    verifyWithBank: ['rate'],
  },
  scheme_standup_india: {
    fundingType: 'loan',
    sizeMin: 1000000, sizeMax: 10000000, // repo
    ownContributionPct: () => 10, // guideline
    grant: null,
    rate: { kind: 'unspecified', note: 'Priced at the lender\'s base rate + a margin (MCLR + 3% as listed); the current MCLR is not known to SchemeSetu.' },
    sources: { size: 'repo', rate: 'repo', own: 'guideline' },
    verifyWithBank: ['own_contribution', 'rate'],
  },
  scheme_pm_vishwakarma: {
    fundingType: 'loan_with_grant',
    sizeMin: 0, sizeMax: 300000, // repo
    ownContributionPct: null,
    grant: { kind: 'flat', amount: 15000, timing: 'in_kind' }, // repo: ₹15,000 toolkit support (not cash)
    rate: { kind: 'fixed', value: 5 }, // repo
    tenureDefault: 30, tenureAssumed: true,
    sources: { size: 'repo', rate: 'repo', grant: 'repo' },
    verifyWithBank: ['tenure', 'trade_eligibility'],
    note: 'For traditional artisans and craftspeople in the notified trades.',
    selfConfirm: 'confirm_trade_eligibility', // SchemeSetu cannot check the applicant's trade
  },
  scheme_up_msme_swarozgar: {
    fundingType: 'loan_with_subsidy',
    sizeMin: 100000, sizeMax: 2500000, // repo
    ownContributionPct: null,
    grant: { kind: 'pct_of_cost', pct: () => 25, timing: 'unspecified' }, // repo: up to 25% margin-money subsidy ("up to" — treated as a ceiling)
    grantIsCeiling: true,
    rate: { kind: 'unspecified', note: 'Concessional bank rate; the exact rate is set by the bank.' },
    sources: { size: 'repo', grant: 'repo', rate: 'repo' },
    verifyWithBank: ['subsidy_amount'],
  },
  scheme_bihar_udyam: {
    fundingType: 'grant_plus_loan',
    sizeMin: 200000, sizeMax: 1000000, // repo
    ownContributionPct: null,
    grant: { kind: 'pct_of_cost', pct: () => 50, cap: 500000, timing: 'upfront' }, // repo: 50% grant, ₹5L
    rate: { kind: 'by_gender', female: 0, other: 1 }, // repo: 0% for women, 1% others
    sources: { size: 'repo', grant: 'repo', rate: 'repo' },
    verifyWithBank: [],
  },
  scheme_pmfme: {
    fundingType: 'loan_with_subsidy',
    sizeMin: null, sizeMax: null, // repo gives the subsidy cap, not a project-size cap
    ownContributionPct: null,
    grant: { kind: 'pct_of_cost', pct: () => 35, cap: 1000000, timing: 'back_ended' }, // repo: 35% capital subsidy, max ₹10L
    rate: { kind: 'unspecified', note: 'Bank\'s standard rate applies.' },
    sources: { grant: 'repo', rate: 'repo' },
    verifyWithBank: ['project_cost_limit'],
  },
};

// Schemes that don't hand out money themselves but can make a loan easier.
export const ENABLERS = {
  scheme_cgtmse: 'Collateral-free credit guarantee — ask the lender whether your loan can be covered by CGTMSE so you do not need to pledge security.',
};

const isSpecial = (t, profile) =>
  (t.specialCategories || []).includes(profile.category) || (t.specialIfFemale && profile.gender === 'female');

// Resolve a terms object for one user/situation into plain numbers (or null =
// unknown). `ctx` = { sector, area, profile }.
export function resolveTerms(schemeId, ctx) {
  const t = CURATED_TERMS[schemeId];
  if (!t) return null;
  const c = { sector: ctx.sector, area: ctx.area, special: isSpecial(t, ctx.profile) };
  const grant = t.grant ? {
    kind: t.grant.kind,
    pct: t.grant.pct ? t.grant.pct(c) : null,
    cap: t.grant.cap ?? null,
    amount: t.grant.amount ?? null,
    timing: t.grant.timing,
    isCeiling: Boolean(t.grantIsCeiling),
  } : null;
  return {
    schemeId,
    fundingType: t.fundingType,
    sizeMin: t.sizeMin ?? null,
    sizeMax: typeof t.sizeMax === 'function' ? t.sizeMax(c) : (t.sizeMax ?? null),
    ownContributionPct: t.ownContributionPct ? t.ownContributionPct(c) : null,
    grant,
    rate: t.rate,
    tenureDefault: t.tenureDefault ?? null,
    tenureAssumed: Boolean(t.tenureAssumed),
    verifyWithBank: t.verifyWithBank || [],
    note: t.note || null,
    selfConfirm: t.selfConfirm || null,
    sources: t.sources || {},
  };
}

// The interest rate to compute with, or null when it cannot honestly be known.
// Returns { value, isEstimate, label, basis }.
export function pickRate(rate, { gender, quotedRate }) {
  if (!rate) return null;
  if (rate.kind === 'fixed') return { value: rate.value, isEstimate: false, label: `${rate.value}%`, basis: 'scheme rate' };
  if (rate.kind === 'by_gender') {
    const v = gender === 'female' ? rate.female : rate.other;
    return { value: v, isEstimate: false, label: `${v}%`, basis: gender === 'female' ? 'scheme rate for women' : 'scheme rate' };
  }
  if (rate.kind === 'range') {
    const mid = (rate.min + rate.max) / 2;
    return { value: mid, isEstimate: true, label: `~${mid}% (range ${rate.min}%–${rate.max}%)`, basis: 'midpoint of the published range — the lender sets the final rate' };
  }
  // 'unspecified': only the user's own bank quote may be used.
  if (Number.isFinite(quotedRate)) return { value: quotedRate, isEstimate: false, label: `${quotedRate}%`, basis: 'the rate you told us your bank quoted' };
  return null;
}

// ---- catalogue (AI-extracted, unverified) loan rows → same shape ----------
export function catalogueTerms(row) {
  const num = (v) => (Number.isFinite(Number(v)) && v !== null ? Number(v) : null);
  const pos = (v) => { const n = num(v); return n && n > 0 ? n : null; }; // 0 in the extraction means "not specified"
  let rate = { kind: 'unspecified', note: 'The official scheme text does not give a usable interest rate.' };
  const rt = row.rate_type;
  const fixed = num(row.interest_rate), lo = num(row.interest_rate_min), hi = num(row.interest_rate_max);
  if (rt === 'official_fixed' && fixed !== null) rate = { kind: 'fixed', value: fixed };
  else if (rt === 'official_range' && lo !== null && hi !== null) rate = { kind: 'range', min: lo, max: hi };
  else if (rt === 'subsidy') {
    const base = fixed ?? (lo !== null && hi !== null ? (lo + hi) / 2 : null);
    const sub = num(row.interest_subsidy_pct);
    if (base !== null) rate = { kind: 'fixed', value: Math.max(0, base - (sub || 0)), derived: true };
  }
  return {
    schemeId: row.slug,
    fundingType: 'loan',
    sizeMin: pos(row.loan_amount_min),
    sizeMax: pos(row.loan_amount_max),
    ownContributionPct: null,
    grant: null,
    rate,
    tenureDefault: null,
    tenureMin: pos(row.tenure_min_months),
    tenureMax: pos(row.tenure_max_months),
    verifyWithBank: ['everything'],
    sources: { all: 'ai_extracted' },
  };
}
